### ISSUE TITLE
Abstract Event Library

### ISSUE THREAD

**Issue by hazen** [basho-labs/riak-c-client#13]
Look at Redis client example https://github.com/redis/hiredis of how to abstract the event library out so we can support more than just libevent.

**Comment by broach** [comment]
I know we talked about this in mumble a little but I wanted to collect my thoughts a bit. I have concerns with doing this right now from a value proposition. 

In my experience, the vast majority of people will simply not care that the client uses libevent. It's a client library to talk to Riak and they'll just use it. There will _always_ be "that person" on the mailing list or whatever that says differently but they're going to be the exception vs. the rule. I would be willing to wager real money that the number of people who would not use our client solely because of the event loop employed is ... very small approaching zero. 

Talking to Mark Phillips, he says that since June he's talked to around 20 companies that have voiced that they would be interested in a C client, one that shall not be named in particular. 

IMHO, releasing the C client with Riak 2.0 and supporting all the 2.0 features should be the goal. If doing this work to abstract the event loop would not be mutually exclusive with achieving that goal then sure ... but already we were talking about the C client not having all the 2.0 features when released so ... I don't see how that's the case. 

I'm not saying that having a pluggable event loop isn't cool or that absolutely no one would use it; I'm making the argument that with the limited time and resources available it simply doesn't deliver a ton of value for Basho, especially weighed against a complete feature set.

**Comment by hazen** [comment]
@broach Good argument. My counter is that if we want to add it, sooner rather than later makes sense. At the very least I want to bury the event library a bit better so we can change it more easily in the future.  I don't think it would be a huge effort, but if it proves to be a pain I agree we can skip it.

Sorry if I mislead you in mumble yesterday by saying it was our top priority.  It was just the top of the list of things to do in my head.

**Comment by broach** [comment]
@javajolt It makes sense from a "this is easier now" standpoint, I agree. I'm just trying to make sure we're not going down a feature rabbit hole here that ends up being the fly in the ointment. Even if it "costs" more to refactor later, IMO that's the better value proposition / tradeoff to getting a complete, usable client done and released sooner. 

If you're confident that doing it now isn't going to be a show stopper in terms of getting the client out with Riak 2.0 then it's all good - having not looked at I don't really have an idea of the amount of work involved.

**Comment by hazen** [comment]
Closing since https://github.com/basho/riak-c-client/pull/23 addresses this
