### ISSUE TITLE
clean up header files, only require a single riak.h

### ISSUE THREAD

**Issue by bookshelfdave** [basho-labs/riak-c-client#9]

**Comment by hazen** [comment]
I think we are already good here, @metadave . Here is the current include list in example.c:

```
#include "riak.h"
#include "riak_command.h"
#include "example_call_backs.h"
#include "../adapters/riak_libevent.h"
#include <time.h>
```

`riak_command.h` is the example command parser and `example_call_backs.h` are async callback stubs for the example.  The only exception is `riak_libevent.h` which I've stuffed into the adapters directory ala https://github.com/redis/hiredis .

Let me know if there you think this issue is still outstanding.
